FROM node:12.13.1
MAINTAINER Rajat Gupta <rajatgupta310198@gmail.com>

WORKDIR /usr/src/app

COPY . /usr/src/app
RUN npm install --silent
RUN npm i -g @nestjs/cli
RUN apt-get update && apt-get -y install build-essential apt-utils


ENV NODE_ENV=development
ENV APP_NAME=avocado-user-service

EXPOSE 3000
CMD ["npm", "run", "start:dev"]